#!/bin/bash

#
#                       /^--^\     /^--^\     /^--^\
#                       \____/     \____/     \____/
#                      /      \   /      \   /      \
#                     |        | |        | |        |
#                      \__  __/   \__  __/   \__  __/
# |^|^|^|^|^|^|^|^|^|^|^|^\ \^|^|^|^/ /^|^|^|^|^\ \^|^|^|^|^|^|^|^|^|^|^|^|
# | | | | | | | | | | | | |\ \| | |/ /| | | | | | \ \ | | | | | | | | | | |
# ########################/ /######\ \###########/ /#######################
# | | | | | | | | | | | | \/| | | | \/| | | | | |\/ | | | | | | | | | | | |
# |_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|

# tails - for when you need to tail more than one thing and you don't want
#         to (or can't) install multitail

if [ -z "$*" ]; then
    echo 'Usage: tails file [file...]'
    exit
fi

TAIL_FILE=$(mktemp)

trap "kill \$(jobs -p); rm $TAIL_FILE" EXIT

for f in "$@"; do
    tail -f "$f" >> TAIL_FILE &
done

tail -f TAIL_FILE
